[package]
name = "nostringer-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
nostr = { git = "https://github.com/rust-nostr/nostr", rev = "31180d7" }
secp256k1 = { version = "0.29", default-features = false, features = [
    "rand",
    "serde",
] }

hashes = { package = "bitcoin_hashes", version = "0.12" }
rand_core = "0.6"
sha2 = "0.10"
thiserror = "1.0"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "ring_signatures"
harness = false

[[bench]]
name = "ecdsa"
harness = false
