name: Benchmarks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allow manual triggering
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install gnuplot
        run: |
          sudo apt update
          sudo apt install -y gnuplot
          gnuplot --version

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run benchmarks
        run: cargo bench

      - name: Create benchmark archive
        run: |
          cd target/criterion
          tar -czf ../../benchmark-report.tar.gz .

      - name: Upload benchmark report
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-report
          path: benchmark-report.tar.gz
          retention-days: 30

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-html-report
          path: target/criterion/report/
          retention-days: 30
